default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files  # Prevent giant files from being committed
      - id: check-ast  # Simply check whether the files parse as valid python
      - id: check-executables-have-shebangs  # Ensure that (non-binary) executables have a shebang
      - id: check-json  # Check json files for parseable syntax
        exclude: (.vscode/settings.json|.devcontainer/devcontainer.json)  # exclude editor generator json file
      - id: check-merge-conflict  # Check for files that contain merge conflict strings
      - id: check-xml  # Check XML files for parseable syntax
      - id: check-yaml  # Checks YAML files for parseable syntax
      - id: end-of-file-fixer  # Ensure that a file is either empty, or ends with one newline
      - id: requirements-txt-fixer  # Sort entries in requirements.txt
      - id: trailing-whitespace  # Trim trailing whitespace
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black  # Format Python code
  - repo: https://github.com/bemeurer/beautysh
    rev: v6.4.3
    hooks:
      - id: beautysh  # Format Shell scripts
        additional_dependencies: [setuptools]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.1.0
    hooks:
    - id: sqlfluff-lint
    - id: sqlfluff-fix
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.8
    hooks:
      - id: uv-lock
