# Use `brew bundle` to run

# Development
brew "bash"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "jq"
brew "tree"
brew "virtualenv"
brew "wget"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "uv"
brew "postman"

# Apps
cask "docker-desktop"
cask "ghostty"
cask "google-chrome"
cask "obsidian"
cask "pika"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "antigravity"
cask "whatsapp"
cask "firefox"

# Fonts (Modernized for Homebrew Cask)
cask "font-jetbrains-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-barlow"
cask "font-lato"
cask "font-open-sans"
cask "font-roboto"
cask "font-ubuntu"
cask "font-source-code-pro"
